### ISSUE TITLE
Use admin notices instead of wp_die if dependencies aren't met

### ISSUE THREAD

**Issue by johnwatkins0** [ivdekov/colby-wp-schedule#5]
See https://codex.wordpress.org/Plugin_API/Action_Reference/admin_notices

**Comment by ivdekov** [comment]
@johnwatkins0 Colby Schedules now displays an admin notice (instead of calling `wp_die`) when the user attempts to activate it and ACF is not activated. 

Additionally, if the user deactivates ACF while Colby Schedules is active, the latter deactivates itself and displays an admin notice.

Do you have any preference for the admin notice type:

**Info**
![notice-info](https://user-images.githubusercontent.com/11216936/33445863-d7ab1c74-d5c3-11e7-8e19-449def05b576.png)
**Warning**
![notice-warning](https://user-images.githubusercontent.com/11216936/33445750-7719114a-d5c3-11e7-94fb-c9e70db0f620.png)
**Error**
![notice-error](https://user-images.githubusercontent.com/11216936/33445868-dc74c73c-d5c3-11e7-9619-04ec081d4909.png)

**Comment by johnwatkins0** [comment]
@ivdekov I think something that completely shuts down plugin activation is an error.
